config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home', as: :home
  resources :products do
    resources :reviews, only: :create
    resources :quantities, only: :create
  end
  resources :quantities, only: [ :update, :destroy ]
  resources :shopping_lists, only: [:show, :update, :destroy, :create] do
    member do
      post :send_list
    end
  end
  resources :reviews, only: :destroy
  resources :chatrooms, only: [ :index, :show, :new, :create ] do
    resources :messages, only: :create
  end
  resources :meals, only: :index
  get "/autocomplete/:query", to: 'products#autocomplete', as: :autocomplete
  get "/api/:query", to: 'products#api', as: :api
  get '/:nickname', to: 'pages#myprofile', as: :myprofile
  patch '/shopping_lists/:id/mark_as_done', to: 'shopping_lists#mark_as_done', as: :mark_as_done
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  belongs_to :user
  has_many :messages, dependent: :destroy

  validates :name, presence: :true
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  def index
    @chatrooms = Chatroom.all
  end

  def show
    @chatroom = Chatroom.find(params[:id])
    @message = Message.new
  end

  def new
    @chatroom = Chatroom.new
  end

  def create
    @chatroom = Chatroom.new(chatroom_params)
    @chatroom.user = current_user
    if @chatroom.save
      redirect_to chatroom_path(@chatroom)
    else
      render :new
    end
  end

  private

  def chatroom_params
    params.require(:chatroom).permit(:name)
  end
end

app/views/chatrooms/index.html.erb
<article class="all-chatrooms container">
  <section class="chatroom-heading">
    <h4 class='sub-heading my-0'>COMMUNITY THREADS</h4>
    <%= link_to new_chatroom_path do %>
      <%= icon('fa', 'edit') %>
    <% end %>
  </section>
  <section class="all-community-threads">
    <% @chatrooms.reverse.each do |chatroom| %>
      <%= link_to chatroom_path(chatroom) do %>
        <div class="community-thread">
          <div class="chatroom-description">
            <% if chatroom.user.avatar.attached? %>
              <%= cl_image_tag chatroom.user.avatar.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
              <%= cl_image_tag "default_avatar_yubqpb", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>
            <div class="chatroom-name-author">
              <p><%= chatroom.name %></p>
              <p><%= chatroom.user.nickname %> · <%= chatroom.messages.count %> comments</p>
            </div>
          </div>
          <% if chatroom.messages.any? %>
            <p class='chatroom-recent-time'>
              <%= distance_of_time_in_words_to_now(chatroom.messages.last.created_at) %>
            </p>
          <% end %>
        </div>
        <hr>
      <% end %>
    <% end %>
  </section>
</article>

app/views/chatrooms/new.html.erb
<article class="container">
  <%= simple_form_for @chatroom do |f| %>
    <%= f.input :name, label: false, placeholder: "What do you need help with?" %>
    <%= f.submit 'Create thread', class: "btn btn-block form-button" %>
  <% end %>
</article>

app/views/chatrooms/show.html.erb
<div class="container">
  <article class="chatroom">
    <div class="chatroom-heading">
      <%= link_to chatrooms_path do %>
        <% icon('fa', 'arrow-circle-left') %>
      <% end %>
      <h4 class="sub-heading"><%= @chatroom.name.upcase %></h4>
      <span></span>
    </div>
    <div id="messages" data-chatroom-id="<%= @chatroom.id %>">
      <% @chatroom.messages.each do |message| %>
        <% if message.user == current_user %>
          <article class="message-container my-message">
            <%= render "messages/message", message: message %>
          </article>
        <% else %>
          <article class="message-container">
            <%= render "messages/message", message: message %>
          </article>
        <% end %>
      <% end %>
    </div>
  </article>

  <%= simple_form_for [ @chatroom, @message ], remote: true do |f| %>
    <div class="field">
      <%#= f.input :content, label: false, placeholder: "Message ##{@chatroom.name}", id: "submit-message" %>
      <%= f.rich_text_area :content, label: false, placeholder:  "Message ##{@chatroom.name}", id: "submit-message" %>
    </div>
  <% end %>
</div>