config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home', as: :home
  resources :products do
    resources :reviews, only: :create
    resources :quantities, only: :create
  end
  resources :quantities, only: [ :update, :destroy ]
  resources :shopping_lists, only: [:show, :update, :destroy, :create] do
    member do
      post :send_list
    end
  end
  resources :reviews, only: :destroy
  resources :chatrooms, only: [ :index, :show, :new, :create ] do
    resources :messages, only: :create
  end
  resources :meals, only: :index
  get "/autocomplete/:query", to: 'products#autocomplete', as: :autocomplete
  get "/api/:query", to: 'products#api', as: :api
  get '/:nickname', to: 'pages#myprofile', as: :myprofile
  patch '/shopping_lists/:id/mark_as_done', to: 'shopping_lists#mark_as_done', as: :mark_as_done
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-light navbar-lewagon">
  <%= link_to "/", class: "navbar-brand" do %>
    <%= cl_image_tag "default_avatar_hvvixr" %>
  <% end %>
  <% if user_signed_in? %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item dropdown">
          <% if current_user.avatar.attached? %>
            <%= cl_image_tag current_user.avatar.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <%= cl_image_tag "default_avatar_yubqpb", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
        </li>
        <% if shopping_list.persisted? %>
          <li class="nav-item">
            <%= link_to "Shopping list", shopping_list_path(shopping_list), class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Shopping list", shopping_lists_path(ShoppingList.new), method: :post, class: "nav-link" %>
          </li>
        <% end %>
        <li class="nav-item">
          <%= link_to "My profile", myprofile_path(current_user.nickname), class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Add an alternative", new_product_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Explore", meals_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Threads", chatrooms_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
      </ul>
    </div>
  <% else %>
    <li class="nav-item nav-link">
      <%= link_to "Login", new_user_session_path %>
    </li>
  <% end %>
</div>

app/views/shared/_product_form.html.erb
<%= simple_form_for @product do |f| %>
  <p>General product information</p>
  <%= f.input :name, label: false, placeholder: 'Product name' %>
  <%= f.input :description, label: false, placeholder: 'Description' %>
  <%= f.input :ingredients, label: false, placeholder: 'Ingredients' %>
  <%= f.input :price_range, collection: ['£', '££', '£££'], label: false, prompt: 'Price range' %>
  <p>Nutrition information</p>
  <%= f.input :calories_per_100g, label: false, placeholder: 'Energy per 100g' %>
  <%= f.input :fat_per_100g, label: false, placeholder: 'Fat per 100g' %>
  <%= f.input :carbs_per_100g, label: false, placeholder: 'Carbohydrate per 100g' %>
  <%= f.input :protein_per_100g, label: false, placeholder: 'Protein per 100g' %>
  <p>How eco-friendly is that product?</p>
  <%= f.input :water_saved, label: false, placeholder: 'Water saved' %>
  <%= f.input :energy_saved, label: false, placeholder: 'Energy saved' %>
  <p>Extra features</p>
  <%= f.input :low_cal, as: :boolean, checked_value: true, unchecked_value: false, boolean_style: :inline, label: 'Low calorie' %>
  <%= f.input :high_protein, as: :boolean, checked_value: true, unchecked_value: false, label: 'High in protein' %>
  <%= f.input :gluten_free, as: :boolean, checked_value: true, unchecked_value: false, label: 'Gluten free' %>
  <p>Add some pictures!</p>
  <%= f.input :photos, as: :file, input_html: { multiple: true }, label: false %>
  <%= f.submit 'Search', class: "btn btn-block form-button" %>
<% end %>

app/views/shared/_quantity_form.html.erb
<!-- Create plus, minus logic for quantity count -->
<!-- <span>+</span>
<span> <%#= @shopping_list.quantities.find_by(#product_id: @product)&.quantity %> </span>
<span>-</span> -->

<%= simple_form_for [ @product, Quantity.new ], method: :post do |f| %>
  <div class="product-quantity">
    <%= f.input :quantity, input_html: { value: 1 }, label: false %>
    <%= f.submit 'Add to list', class: 'quantity-button' %>
  </div>
<% end %>

app/views/shared/_recipe_card.html.erb
<div class="recipes-container">
  <div class="product-cards container">
    <% @recipes.each do |recipe| %>
      <%= link_to recipe.url do %>
        <div class="product-card recipe-card" style="background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.2)), url('<%= image_path recipe.image_url, crop: :fill, width: 360 %>')">
          <%= recipe.name %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/shared/_review_form.html.erb
<%= simple_form_for [ @product, @review ], method: :post, remote: true do |f| %>
  <%= f.input :rating, collection: (1..5).to_a, label: "Rate this item" %>
  <%= f.input :content, label: "Leave your comment here" %>
  <%= f.submit label: "Add Review", class: "review-button" %>
<% end %>

app/views/shared/_search_form.html.erb
<div class="search-form-wrapper">
  <%= form_tag products_path, id: "form_id", method: :get do %>
    <div class="d-inline-block search-form">
      <%= text_field_tag :query,
        params[:query],
        class: "search-input",
        placeholder: "Find a product"
      %>
      <%= button_tag(type: "submit", class: "search-form-button") do %>
        <i class="fa fa-search icon"></i>
      <% end %>
    </div>
  <% end %>
  <div id="autocomplete-suggestions"></div>
</div>