config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home', as: :home
  resources :products do
    resources :reviews, only: :create
    resources :quantities, only: :create
  end
  resources :quantities, only: [ :update, :destroy ]
  resources :shopping_lists, only: [:show, :update, :destroy, :create] do
    member do
      post :send_list
    end
  end
  resources :reviews, only: :destroy
  resources :chatrooms, only: [ :index, :show, :new, :create ] do
    resources :messages, only: :create
  end
  resources :meals, only: :index
  get "/autocomplete/:query", to: 'products#autocomplete', as: :autocomplete
  get "/api/:query", to: 'products#api', as: :api
  get '/:nickname', to: 'pages#myprofile', as: :myprofile
  patch '/shopping_lists/:id/mark_as_done', to: 'shopping_lists#mark_as_done', as: :mark_as_done
end

app/models/shopping_list.rb
class ShoppingList < ApplicationRecord
  belongs_to :user
  has_many :quantities, dependent: :destroy
  has_many :products, through: :quantities
end

app/controllers/shopping_lists_controller.rb
class ShoppingListsController < ApplicationController
  before_action :find_list, only: [ :show, :update, :destroy, :mark_as_done, :send_list ]

  def show;  end

  def create
    @shopping_list = ShoppingList.new
    @shopping_list.date = Date.today
    @shopping_list.user = current_user
    if @shopping_list.save
      redirect_to shopping_list_path(@shopping_list)
    else
      redirect_to home_path
    end
  end

  def update
    @shopping_list.update()
  end

  def mark_as_done
    @shopping_list.mark_as_done = true
    @shopping_list.save

    redirect_to myprofile_path(current_user)
  end

  def send_list
    @shopping_list.mark_as_done = true
    @shopping_list.save
    ShoppingListMailer.with(shopping_list: @shopping_list).shopping_list.deliver_now
    redirect_to myprofile_path(current_user), notice: "Email sent"
  end

  def destroy
    @shopping_list.destroy

    redirect_to myprofile_path(current_user)
  end

  private

  def find_list
    @shopping_list = ShoppingList.find(params[:id])
  end
end

app/views/shopping_lists/show.html.erb
<div class="container shopping-list-page">
  <%#= link_to "Send shopping list", send_list_shopping_list_path(@shopping_list), method: :post %>
  <h4 class="green-header">MY SHOPPING LIST</h4>
  <% if @shopping_list.quantities.empty? %>
    <div class="empty-list">
      <p>There are no items in your shopping list</p>
      <%= link_to products_path do %>
        <button type="button" class='form-button'>Start browsing</button>
      <% end %>
    </div>
  <% else %>
    <% if !@shopping_list.mark_as_done %>
      <table class="styled-table sl-table">
        <th class="table-header">Product name</th>
        <th class="table-header" style="margin-left: 35px";>Quantity</th>
        <th class="table-header"></th>
        <% @shopping_list.quantities.each do |quantity| %>
          <tr class="quantity-row">
            <td class="black name-table"><%= quantity.product.name %></td>
            <td>
              <%= simple_form_for quantity, method: :patch do |f| %>
                <div >
                  <%= f.input :quantity, input_html: { min: '0' }, class: "quantity-input", label: false %>
                </div>
              <% end %>
            </td>
            <td class="table-bin green-link"><%= link_to quantity_path(quantity), method: :delete, data: { confirm: 'Are you sure?' } do %>
              <%= icon("fa", "trash") %>
            <% end %></td>
          </tr>
          <tr>
            <td class='shopping-list-stores'>
              <% nearest_store = quantity.product.stores.select { |store| store.latitude.is_a?(Float) && store.longitude.is_a?(Float) }.sort_by { |store| store.distance_to(@user_location) }.first || quantity.product.stores.sample %>
              <p><%= nearest_store.name %> · <%= nearest_store.address.split(",").first %></p>
              <div class="collapsible-tray">
                <p class="collapsible">See more locations <%= icon("fa", "chevron-circle-down") %></p>
                <div class="content">
                  <% remaining_stores = quantity.product.stores.reject { |store| store == nearest_store } %>
                  <% if remaining_stores.any? %>
                    <% remaining_stores.each do |remaining_store| %>
                      <%= remaining_store.name %> · <%= remaining_store.address.split(",").first %>
                      <br>
                    <% end %>
                  <% else %>
                    <p>This item is only available in <%= nearest_store.name %>.</p>
                  <% end %>
                </div>
              </div>
            </td>
          </tr>
        <% end %>
      </table>
    <% else %>
      <table class="styled-table sl-table">
        <th class="table-header">Product name</th>
        <th class="table-header" style="padding-right: 15px;">Quantity</th>
        <% @shopping_list.quantities.each do |quantity| %>
          <tr>
            <td class="black name-table"><%= quantity.product.name %></td>
            <td class="black center" style="padding-right: 30px;"><%= quantity.quantity %></td>
          </tr>
        <% end %>
      </table>
    <% end %>
  <% end %>

  <br>
  <h4 class="green-header">LIST ECO-SCORE</h4>
  <section class="my-eco-score">
    <% water = 0 %>
    <% energy = 0 %>
    <% @shopping_list.quantities.each do |q| %>
      <% water += q.product.water_saved * q.quantity %>
      <% energy += q.product.energy_saved * q.quantity %>
    <% end %>
    <div class="eco-score">
      <div class="emoji"><p id="drop">💧</p></div>
      <div class="sum-saved">
        <h5 class="black"> <strong> <%= water %> L </strong></h5>
        <p> of water </p>
      </div>
    </div>
    <div class="eco-score">
      <div class="emoji"><p>✈️</p></div>
      <div class="sum-saved">
        <h5 class="black"> <strong> <%= energy %> kg </strong></h5>
        <p> of CO2 </p>
      </div>
    </div>
  </section>
</div>


  <% if @shopping_list.mark_as_done == false %>
    <footer class="results-footer-sl">
      <%= link_to send_list_shopping_list_path(@shopping_list), method: :post do %>
      <%#= link_to mark_as_done_path(@shopping_list), method: :patch do %>
        <button type="button" class="quantity-button-sl">Send shopping list</button>
    </footer>
  <% end %>
<% end %>